-- Historical EF schema from subscrio-dotnet commit ab3c851 (before entitlement changes).
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'subscrio') THEN
        CREATE SCHEMA subscrio;
    END IF;
END $EF$;


CREATE TABLE subscrio.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL,
    display_name text,
    email text,
    external_billing_id text,
    status text NOT NULL,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_customers" PRIMARY KEY (id)
);


CREATE TABLE subscrio.features (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL,
    display_name text NOT NULL,
    description text,
    value_type text NOT NULL,
    default_value text NOT NULL,
    group_name text,
    status text NOT NULL,
    validator jsonb,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_features" PRIMARY KEY (id)
);


CREATE TABLE subscrio.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL,
    display_name text NOT NULL,
    description text,
    status text NOT NULL,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_products" PRIMARY KEY (id)
);


CREATE TABLE subscrio.system_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    config_key text NOT NULL,
    config_value text NOT NULL,
    encrypted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_system_config" PRIMARY KEY (id)
);


CREATE TABLE subscrio.product_features (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    feature_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_product_features" PRIMARY KEY (id),
    CONSTRAINT "FK_product_features_features_feature_id" FOREIGN KEY (feature_id) REFERENCES subscrio.features (id) ON DELETE CASCADE,
    CONSTRAINT "FK_product_features_products_product_id" FOREIGN KEY (product_id) REFERENCES subscrio.products (id) ON DELETE CASCADE
);


CREATE TABLE subscrio.billing_cycles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    plan_id bigint NOT NULL,
    key text NOT NULL,
    display_name text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'active',
    duration_value integer,
    duration_unit text NOT NULL,
    external_product_id text,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_billing_cycles" PRIMARY KEY (id)
);


CREATE TABLE subscrio.plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    product_id bigint NOT NULL,
    key text NOT NULL,
    display_name text NOT NULL,
    description text,
    status text NOT NULL,
    on_expire_transition_to_billing_cycle_id bigint,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_plans" PRIMARY KEY (id),
    CONSTRAINT "FK_plans_billing_cycles_on_expire_transition_to_billing_cycle_~" FOREIGN KEY (on_expire_transition_to_billing_cycle_id) REFERENCES subscrio.billing_cycles (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_plans_products_product_id" FOREIGN KEY (product_id) REFERENCES subscrio.products (id) ON DELETE CASCADE
);


CREATE TABLE subscrio.plan_features (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    plan_id bigint NOT NULL,
    feature_id bigint NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_plan_features" PRIMARY KEY (id),
    CONSTRAINT "FK_plan_features_features_feature_id" FOREIGN KEY (feature_id) REFERENCES subscrio.features (id) ON DELETE CASCADE,
    CONSTRAINT "FK_plan_features_plans_plan_id" FOREIGN KEY (plan_id) REFERENCES subscrio.plans (id) ON DELETE CASCADE
);


CREATE TABLE subscrio.subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL,
    customer_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    billing_cycle_id bigint NOT NULL,
    activation_date timestamp with time zone,
    expiration_date timestamp with time zone,
    cancellation_date timestamp with time zone,
    trial_end_date timestamp with time zone,
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    stripe_subscription_id text,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    is_archived boolean NOT NULL DEFAULT FALSE,
    transitioned_at timestamp with time zone,
    CONSTRAINT "PK_subscriptions" PRIMARY KEY (id),
    CONSTRAINT "FK_subscriptions_billing_cycles_billing_cycle_id" FOREIGN KEY (billing_cycle_id) REFERENCES subscrio.billing_cycles (id) ON DELETE CASCADE,
    CONSTRAINT "FK_subscriptions_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES subscrio.customers (id) ON DELETE CASCADE,
    CONSTRAINT "FK_subscriptions_plans_plan_id" FOREIGN KEY (plan_id) REFERENCES subscrio.plans (id) ON DELETE CASCADE
);


CREATE TABLE subscrio.subscription_feature_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    subscription_id bigint NOT NULL,
    feature_id bigint NOT NULL,
    value text NOT NULL,
    override_type text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_subscription_feature_overrides" PRIMARY KEY (id),
    CONSTRAINT "FK_subscription_feature_overrides_features_feature_id" FOREIGN KEY (feature_id) REFERENCES subscrio.features (id) ON DELETE CASCADE,
    CONSTRAINT "FK_subscription_feature_overrides_subscriptions_subscription_id" FOREIGN KEY (subscription_id) REFERENCES subscrio.subscriptions (id) ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_billing_cycles_plan_id_key" ON subscrio.billing_cycles (plan_id, key);


CREATE UNIQUE INDEX "IX_customers_external_billing_id" ON subscrio.customers (external_billing_id) WHERE external_billing_id IS NOT NULL;


CREATE UNIQUE INDEX "IX_customers_key" ON subscrio.customers (key);


CREATE UNIQUE INDEX "IX_features_key" ON subscrio.features (key);


CREATE INDEX "IX_plan_features_feature_id" ON subscrio.plan_features (feature_id);


CREATE UNIQUE INDEX "IX_plan_features_plan_id_feature_id" ON subscrio.plan_features (plan_id, feature_id);


CREATE INDEX "IX_plans_on_expire_transition_to_billing_cycle_id" ON subscrio.plans (on_expire_transition_to_billing_cycle_id);


CREATE UNIQUE INDEX "IX_plans_product_id_key" ON subscrio.plans (product_id, key);


CREATE INDEX "IX_product_features_feature_id" ON subscrio.product_features (feature_id);


CREATE UNIQUE INDEX "IX_product_features_product_id_feature_id" ON subscrio.product_features (product_id, feature_id);


CREATE UNIQUE INDEX "IX_products_key" ON subscrio.products (key);


CREATE INDEX "IX_subscription_feature_overrides_feature_id" ON subscrio.subscription_feature_overrides (feature_id);


CREATE UNIQUE INDEX "IX_subscription_feature_overrides_subscription_id_feature_id" ON subscrio.subscription_feature_overrides (subscription_id, feature_id);


CREATE INDEX "IX_subscriptions_billing_cycle_id" ON subscrio.subscriptions (billing_cycle_id);


CREATE INDEX "IX_subscriptions_customer_id" ON subscrio.subscriptions (customer_id);


CREATE UNIQUE INDEX "IX_subscriptions_key" ON subscrio.subscriptions (key);


CREATE INDEX "IX_subscriptions_plan_id" ON subscrio.subscriptions (plan_id);


CREATE UNIQUE INDEX "IX_subscriptions_stripe_subscription_id" ON subscrio.subscriptions (stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL;


CREATE UNIQUE INDEX "IX_system_config_config_key" ON subscrio.system_config (config_key);


ALTER TABLE subscrio.billing_cycles ADD CONSTRAINT "FK_billing_cycles_plans_plan_id" FOREIGN KEY (plan_id) REFERENCES subscrio.plans (id) ON DELETE CASCADE;
